env: 
 CONCURRENCY_GROUP: "${CONCURRENCY_GROUP:-test_group}"
 QUICKSTART_FILE: "deprecation.sh"
steps:
  - label: "Multiline Command Test"
    command: |
      echo "Testing multiple commands"
      echo "This is a multiline script"
      if [ -z "$BUILDKITE_AGENT_META_DATA_QUEUE" ]; then
        echo "Environment variable is not set"
      else
        echo "Environment variable is set"
      fi
    signature: 
        value: "eyJhbGciOiJQUzUxMiIsImtpZCI6InByb2QifQ..XkPFgU-Pz3NM33cIjlgBZE5MgqTsb4LnII4gKhfHe417MC9LxpuBrVwng5ubzrQ2ot8CySYXKMtYEu0qKNjsQlWAMmGEG0JaYx9DhC3Nh3AqNxuV_bRknNlB0IrrWlnJmxBGTBTP1LbOU0b656CZ3vefmwPmbxHJCZZtK-jN2zAKyDU6370FShlR7QBC_exZTcMsGl8WG7i532LXGy3KswY4q08ZKJlyaRSEXUKYJaTi8o48a0ASF4cPDaRfmlGpIy5UJq-KzqUARIWBqhiUkQ_2PPO-WyP3_v8QpoCCMMLHTgwzkqQox6hm8_a9_dx1lhb8cI_SzERUkjSTAMow5Q"
        algoritm: "PS512"
    agents:
      queue: "mac"

  - label: "Single Line Command Test"
    command: "echo 'Testing single line' && echo 'This should work fine'"
    signature: 
        value: "eyJhbGciOiJQUzUxMiIsImtpZCI6InByb2QifQ..XkPFgU-Pz3NM33cIjlgBZE5MgqTsb4LnII4gKhfHe417MC9LxpuBrVwng5ubzrQ2ot8CySYXKMtYEu0qKNjsQlWAMmGEG0JaYx9DhC3Nh3AqNxuV_bRknNlB0IrrWlnJmxBGTBTP1LbOU0b656CZ3vefmwPmbxHJCZZtK-jN2zAKyDU6370FShlR7QBC_exZTcMsGl8WG7i532LXGy3KswY4q08ZKJlyaRSEXUKYJaTi8o48a0ASF4cPDaRfmlGpIy5UJq-KzqUARIWBqhiUkQ_2PPO-WyP3_v8QpoCCMMLHTgwzkqQox6hm8_a9_dx1lhb8cI_SzERUkjSTAMow5Q"
        algoritm: "PS512"
    agents:
      queue: "mac"

  - label: "Check Quickstart File"
    command: |
      ls -la
      echo "Check if $$QUICKSTART_FILE exists..."
      if [ ! -f "$$QUICKSTART_FILE" ]; then
          echo -e "\033[31m$$QUICKSTART_FILE does not exist\033[0m"
          exit 1
      fi
    agents:
      queue: "mac"
  # Integration of new test scenarios
  - label: "Test Dynamic Var Escaping with Double Dollar"
    commands:
      - "if [[ -z \"$$CONCURRENCY_GROUP\" ]]; then echo \"Error, $$CONCURRENCY_GROUP is empty. Please set this environment variable.\"; exit 1; fi"
      - "cat .buildkite/benchmarking.yml | sed 's/%concurrency_group%/$$CONCURRENCY_GROUP/' | buildkite-agent pipeline upload"
    agents:
      queue: "mac"

  - label: "Test Dynamic Var Escaping with Single Dollar"
    commands:
      - "if [[ -z \"$CONCURRENCY_GROUP\" ]]; then echo \"Error, $CONCURRENCY_GROUP is empty. Please set this environment variable.\"; exit 1; fi"
      - "cat .buildkite/benchmarking.yml | sed 's/%concurrency_group%/$CONCURRENCY_GROUP/' | buildkite-agent pipeline upload"
    agents:
      queue: "mac"
      
      

      
