env: 
 CONCURRENCY_GROUP: "${CONCURRENCY_GROUP:-test_group}"
 QUICKSTART_FILE: "deprecation.sh"
steps:
  - label: "Multiline Command Test"
    command: |
      echo "Testing multiple commands"
      echo "This is a multiline script"
      if [ -z "$BUILDKITE_AGENT_META_DATA_QUEUE" ]; then
        echo "Environment variable is not set"
      else
        echo "Environment variable is set"
      fi
    signature: 
        value: "eyJhbGciOiJQUzUxMiIsImtpZCI6InByb2QifQ..jrZTHomIqTYUzbxBebAZ9qOI1wZE1PdFA2vPRdZN6a22SxKPHsHcWLhY_blP1z3vA24l71LSD3Az0qu87ZtiyC0j3n4s8nwyjNjQGxYKNk2W2YXAWnqT_65XcjKsLJs8tKGtDYumlkXUdEUknsbcjHwW-arGXsZsDOa64fHnmdxui-epkeQOA875hDO5811K4hIl1SYvzzMeERnuZwoL5BNJ5jxrOYvEsJOdG78Gf9QxdaCpA4lYJdeMyrHesN_yypsIbUCJjLNlzXYQjn2ckS-HSq1xcLfvzLjc7zC753X1yUYM5uVK9zX_hKE701zPHrC87TQobB8GpLGrCoYLOw"
        algoritm: "PS512"
    agents:
      queue: "mac"

  - label: "Single Line Command Test"
    command: "echo 'Testing single line' && echo 'This should work fine'"
    signature: 
        value: "eyJhbGciOiJQUzUxMiIsImtpZCI6InByb2QifQ..jrZTHomIqTYUzbxBebAZ9qOI1wZE1PdFA2vPRdZN6a22SxKPHsHcWLhY_blP1z3vA24l71LSD3Az0qu87ZtiyC0j3n4s8nwyjNjQGxYKNk2W2YXAWnqT_65XcjKsLJs8tKGtDYumlkXUdEUknsbcjHwW-arGXsZsDOa64fHnmdxui-epkeQOA875hDO5811K4hIl1SYvzzMeERnuZwoL5BNJ5jxrOYvEsJOdG78Gf9QxdaCpA4lYJdeMyrHesN_yypsIbUCJjLNlzXYQjn2ckS-HSq1xcLfvzLjc7zC753X1yUYM5uVK9zX_hKE701zPHrC87TQobB8GpLGrCoYLOw"
        algoritm: "PS512"
    agents:
      queue: "mac"

  - label: "Check Quickstart File"
    command: |
      ls -la
      echo "Check if $$QUICKSTART_FILE exists..."
      if [ ! -f "$$QUICKSTART_FILE" ]; then
          echo -e "\033[31m$$QUICKSTART_FILE does not exist\033[0m"
          exit 1
      fi
    agents:
      queue: "mac"
  # Integration of new test scenarios
  - label: "Test Dynamic Var Escaping with Double Dollar"
    commands:
      - "if [[ -z \"$$CONCURRENCY_GROUP\" ]]; then echo \"Error, $$CONCURRENCY_GROUP is empty. Please set this environment variable.\"; exit 1; fi"
      - "cat .buildkite/benchmarking.yml | sed 's/%concurrency_group%/$$CONCURRENCY_GROUP/' | buildkite-agent pipeline upload"
    agents:
      queue: "mac"

  - label: "Test Dynamic Var Escaping with Single Dollar"
    commands:
      - "if [[ -z \"$CONCURRENCY_GROUP\" ]]; then echo \"Error, $CONCURRENCY_GROUP is empty. Please set this environment variable.\"; exit 1; fi"
      - "cat .buildkite/benchmarking.yml | sed 's/%concurrency_group%/$CONCURRENCY_GROUP/' | buildkite-agent pipeline upload"
    agents:
      queue: "mac"
      
      

      
